CREATE TABLE `llantas` (
  `id_llanta` int unsigned NOT NULL AUTO_INCREMENT,
  `id_orden` int unsigned NOT NULL,
  `id_marca` int unsigned DEFAULT NULL,
  `id_dimension` int unsigned DEFAULT NULL,
  `id_banda` int unsigned DEFAULT NULL,
  `serie` varchar(50) DEFAULT NULL,
  `prioridad` tinyint DEFAULT '0',
  `observacion` varchar(255) DEFAULT NULL,
  `consec_orden` int NOT NULL,
  `id_estado` int NOT NULL DEFAULT '0',
  `fecha_inspeccion_inicial` datetime DEFAULT NULL,
  `fecha_registro_inspinicial` datetime DEFAULT NULL,
  `id_inspector_inicial` mediumint unsigned DEFAULT NULL,
  `nivel_reenc` tinyint unsigned DEFAULT '0',
  `id_inspec` smallint unsigned DEFAULT '0',
  `observaciones_inicial` text,
  PRIMARY KEY (`id_llanta`),
  KEY `id_orden` (`id_orden`),
  KEY `llantas_ibfk_2` (`id_marca`),
  KEY `llantas_ibfk_3` (`id_dimension`),
  KEY `llantas_ibfk_4` (`id_banda`),
  KEY `fk_estado_llanta` (`id_estado`),
  KEY `fk_inspector_inicial` (`id_inspector_inicial`),
  CONSTRAINT `fk_estado_llanta` FOREIGN KEY (`id_estado`) REFERENCES `estados_llanta` (`id_estado`),
  CONSTRAINT `fk_inspector_inicial` FOREIGN KEY (`id_inspector_inicial`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `llantas_ibfk_1` FOREIGN KEY (`id_orden`) REFERENCES `ordenes` (`id_orden`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_2` FOREIGN KEY (`id_marca`) REFERENCES `marcas` (`id_marca`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_3` FOREIGN KEY (`id_dimension`) REFERENCES `dimensiones` (`id_dimension`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_4` FOREIGN KEY (`id_banda`) REFERENCES `bandas` (`id_banda`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb3