CREATE TABLE `llantas` (
  `id_llanta` int unsigned NOT NULL AUTO_INCREMENT,
  `id_orden` int unsigned NOT NULL,
  `id_marca` int unsigned DEFAULT NULL,
  `id_dimension` int unsigned DEFAULT NULL,
  `id_banda` int unsigned DEFAULT NULL,
  `serie` varchar(50) DEFAULT NULL,
  `prioridad` tinyint DEFAULT '0',
  `observacion` varchar(255) DEFAULT NULL,
  `consec_orden` int NOT NULL,
  `id_estado` int NOT NULL DEFAULT '0',
  `fecha_inspeccion_inicial` datetime DEFAULT NULL,
  `fecha_registro_inspinicial` datetime DEFAULT NULL,
  `id_inspector_inicial` mediumint unsigned DEFAULT NULL,
  `nivel_reenc` tinyint unsigned DEFAULT '0',
  `id_inspec` smallint unsigned DEFAULT '0',
  `observaciones_inicial` text,
  `radio_r` smallint unsigned DEFAULT NULL,
  `perimetro` smallint unsigned DEFAULT NULL,
  `ancho` smallint unsigned DEFAULT NULL,
  `retiro_cinturon` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `fecha_raspado` datetime DEFAULT NULL,
  `fecha_registro_raspado` datetime DEFAULT NULL,
  `id_operario_raspado` mediumint unsigned DEFAULT NULL,
  `id_resolucion_raspado` smallint unsigned DEFAULT NULL,
  `fecha_preparacion` datetime DEFAULT NULL,
  `fecha_registro_preparacion` datetime DEFAULT NULL,
  `id_operario_preparacion` mediumint unsigned DEFAULT NULL,
  `id_resolucion_preparacion` smallint unsigned DEFAULT NULL,
  `fecha_reparacion` datetime DEFAULT NULL,
  `fecha_registro_reparacion` datetime DEFAULT NULL,
  `id_operario_reparacion` mediumint unsigned DEFAULT NULL,
  `id_resolucion_reparacion` smallint unsigned DEFAULT NULL,
  `fecha_relleno` datetime DEFAULT NULL,
  `fecha_registro_relleno` datetime DEFAULT NULL,
  `id_operario_relleno` mediumint unsigned DEFAULT NULL,
  `id_resolucion_relleno` smallint unsigned DEFAULT NULL,
  PRIMARY KEY (`id_llanta`),
  KEY `id_orden` (`id_orden`),
  KEY `llantas_ibfk_2` (`id_marca`),
  KEY `llantas_ibfk_3` (`id_dimension`),
  KEY `llantas_ibfk_4` (`id_banda`),
  KEY `fk_estado_llanta` (`id_estado`),
  KEY `fk_inspector_inicial` (`id_inspector_inicial`),
  KEY `fk_operario_raspado` (`id_operario_raspado`),
  KEY `fk_resolucion_raspado` (`id_resolucion_raspado`),
  KEY `fk_operario_preparacion` (`id_operario_preparacion`),
  KEY `fk_resolucion_preparacion` (`id_resolucion_preparacion`),
  KEY `fk_operario_reparacion` (`id_operario_reparacion`),
  KEY `fk_resolucion_reparacion` (`id_resolucion_reparacion`),
  KEY `fk_operario_relleno` (`id_operario_relleno`),
  KEY `fk_resolucion_relleno` (`id_resolucion_relleno`),
  CONSTRAINT `fk_estado_llanta` FOREIGN KEY (`id_estado`) REFERENCES `estados_llanta` (`id_estado`),
  CONSTRAINT `fk_inspector_inicial` FOREIGN KEY (`id_inspector_inicial`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_operario_raspado` FOREIGN KEY (`id_operario_raspado`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_raspado` FOREIGN KEY (`id_resolucion_raspado`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_preparacion` FOREIGN KEY (`id_operario_preparacion`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_preparacion` FOREIGN KEY (`id_resolucion_preparacion`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_reparacion` FOREIGN KEY (`id_operario_reparacion`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_reparacion` FOREIGN KEY (`id_resolucion_reparacion`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_relleno` FOREIGN KEY (`id_operario_relleno`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_relleno` FOREIGN KEY (`id_resolucion_relleno`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `llantas_ibfk_1` FOREIGN KEY (`id_orden`) REFERENCES `ordenes` (`id_orden`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_2` FOREIGN KEY (`id_marca`) REFERENCES `marcas` (`id_marca`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_3` FOREIGN KEY (`id_dimension`) REFERENCES `dimensiones` (`id_dimension`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_4` FOREIGN KEY (`id_banda`) REFERENCES `bandas` (`id_banda`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb3
