CREATE TABLE `llantas` (
  `id_llanta` int unsigned NOT NULL AUTO_INCREMENT,
  `id_orden` int unsigned NOT NULL,
  `id_marca` int unsigned DEFAULT NULL,
  `id_dimension` int unsigned DEFAULT NULL,
  `id_banda` int unsigned DEFAULT NULL,
  `serie` varchar(50) DEFAULT NULL,
  `prioridad` tinyint DEFAULT '0',
  `observacion` varchar(255) DEFAULT NULL,
  `consec_orden` int NOT NULL,
  `id_estado` int NOT NULL DEFAULT '0',
  `fecha_inspeccion_inicial` datetime DEFAULT NULL,
  `fecha_registro_inspinicial` datetime DEFAULT NULL,
  `id_inspector_inicial` mediumint unsigned DEFAULT NULL,
  `nivel_reenc` tinyint unsigned DEFAULT '0',
  `id_inspec` smallint unsigned DEFAULT '0',
  `observaciones_inicial` text,
  `radio_r` smallint unsigned DEFAULT NULL,
  `perimetro` smallint unsigned DEFAULT NULL,
  `ancho` smallint unsigned DEFAULT NULL,
  `retiro_cinturon` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `fecha_raspado` datetime DEFAULT NULL,
  `fecha_registro_raspado` datetime DEFAULT NULL,
  `id_operario_raspado` mediumint unsigned DEFAULT NULL,
  `id_resolucion_raspado` smallint unsigned DEFAULT NULL,
  `fecha_preparacion` datetime DEFAULT NULL,
  `fecha_registro_preparacion` datetime DEFAULT NULL,
  `id_operario_preparacion` mediumint unsigned DEFAULT NULL,
  `id_resolucion_preparacion` smallint unsigned DEFAULT NULL,
  `fecha_reparacion` datetime DEFAULT NULL,
  `fecha_registro_reparacion` datetime DEFAULT NULL,
  `id_operario_reparacion` mediumint unsigned DEFAULT NULL,
  `id_resolucion_reparacion` smallint unsigned DEFAULT NULL,
  `fecha_relleno` datetime DEFAULT NULL,
  `fecha_registro_relleno` datetime DEFAULT NULL,
  `id_operario_relleno` mediumint unsigned DEFAULT NULL,
  `id_resolucion_relleno` smallint unsigned DEFAULT NULL,
  `fecha_corte` datetime DEFAULT NULL,
  `fecha_registro_corte` datetime DEFAULT NULL,
  `id_operario_corte` mediumint unsigned DEFAULT NULL,
  `fecha_embandado` datetime DEFAULT NULL,
  `fecha_registro_embandado` datetime DEFAULT NULL,
  `id_operario_embandado` mediumint unsigned DEFAULT NULL,
  `id_resolucion_embandado` smallint unsigned DEFAULT NULL,
  `fecha_vulcanizado` datetime DEFAULT NULL,
  `fecha_registro_vulcanizado` datetime DEFAULT NULL,
  `id_operario_vulcanizado` mediumint unsigned DEFAULT NULL,
  `id_resolucion_vulcanizado` smallint unsigned DEFAULT NULL,
  `fecha_inspeccion_final` datetime DEFAULT NULL,
  `fecha_registro_inspeccion_final` datetime DEFAULT NULL,
  `id_operario_inspeccion_final` mediumint unsigned DEFAULT NULL,
  `id_resolucion_inspeccion_final` smallint unsigned DEFAULT NULL,
  `fecha_terminacion` datetime DEFAULT NULL,
  `fecha_registro_terminacion` datetime DEFAULT NULL,
  `id_operario_terminacion` mediumint unsigned DEFAULT NULL,
  `id_resolucion_terminacion` smallint unsigned DEFAULT NULL,
  -- Ubicacion general: P planta, B bodega y C cliente. La bodega concreta se
  -- guarda por id para permitir traslados sin alterar el historial de salida.
  `ubicacion` varchar(10) NOT NULL DEFAULT 'P',
  `documento_salida` mediumint unsigned DEFAULT NULL,
  `fecha_salida` date DEFAULT NULL,
  `id_empleado_salida` mediumint unsigned DEFAULT NULL,
  `id_bodega_salida` smallint unsigned DEFAULT NULL,
  `id_bodega_actual` smallint unsigned DEFAULT NULL,
  `tipo_salida` varchar(20) DEFAULT NULL,
  -- El estimado se guarda al salir y el costo real se completa en el recosteo
  -- mensual, sin perder el valor usado originalmente para el documento.
  `peso_banda_costeo` decimal(8,3) unsigned DEFAULT NULL,
  `costo_kg_estimado_aplicado` decimal(12,2) unsigned DEFAULT NULL,
  `costo_estimado` decimal(12,2) unsigned DEFAULT NULL,
  `costo_kg_real_aplicado` decimal(12,2) unsigned DEFAULT NULL,
  `costo_real` decimal(12,2) unsigned DEFAULT NULL,
  `mes_proceso` tinyint unsigned DEFAULT NULL,
  `anio_proceso` smallint unsigned DEFAULT NULL,
  PRIMARY KEY (`id_llanta`),
  KEY `id_orden` (`id_orden`),
  KEY `llantas_ibfk_2` (`id_marca`),
  KEY `llantas_ibfk_3` (`id_dimension`),
  KEY `llantas_ibfk_4` (`id_banda`),
  KEY `fk_estado_llanta` (`id_estado`),
  KEY `fk_inspector_inicial` (`id_inspector_inicial`),
  KEY `fk_operario_raspado` (`id_operario_raspado`),
  KEY `fk_resolucion_raspado` (`id_resolucion_raspado`),
  KEY `fk_operario_preparacion` (`id_operario_preparacion`),
  KEY `fk_resolucion_preparacion` (`id_resolucion_preparacion`),
  KEY `fk_operario_reparacion` (`id_operario_reparacion`),
  KEY `fk_resolucion_reparacion` (`id_resolucion_reparacion`),
  KEY `fk_operario_relleno` (`id_operario_relleno`),
  KEY `fk_resolucion_relleno` (`id_resolucion_relleno`),
  KEY `fk_operario_corte` (`id_operario_corte`),
  KEY `fk_operario_embandado` (`id_operario_embandado`),
  KEY `fk_resolucion_embandado` (`id_resolucion_embandado`),
  KEY `fk_operario_vulcanizado` (`id_operario_vulcanizado`),
  KEY `fk_resolucion_vulcanizado` (`id_resolucion_vulcanizado`),
  KEY `fk_operario_inspeccion_final` (`id_operario_inspeccion_final`),
  KEY `fk_resolucion_inspeccion_final` (`id_resolucion_inspeccion_final`),
  KEY `fk_operario_terminacion` (`id_operario_terminacion`),
  KEY `fk_resolucion_terminacion` (`id_resolucion_terminacion`),
  KEY `idx_llantas_salida_documento` (`documento_salida`),
  KEY `idx_llantas_salida_disponibles` (`ubicacion`,`id_estado`),
  KEY `fk_empleado_salida` (`id_empleado_salida`),
  KEY `fk_bodega_salida` (`id_bodega_salida`),
  KEY `fk_bodega_actual` (`id_bodega_actual`),
  CONSTRAINT `fk_estado_llanta` FOREIGN KEY (`id_estado`) REFERENCES `estados_llanta` (`id_estado`),
  CONSTRAINT `fk_inspector_inicial` FOREIGN KEY (`id_inspector_inicial`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_operario_raspado` FOREIGN KEY (`id_operario_raspado`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_raspado` FOREIGN KEY (`id_resolucion_raspado`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_preparacion` FOREIGN KEY (`id_operario_preparacion`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_preparacion` FOREIGN KEY (`id_resolucion_preparacion`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_reparacion` FOREIGN KEY (`id_operario_reparacion`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_reparacion` FOREIGN KEY (`id_resolucion_reparacion`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_relleno` FOREIGN KEY (`id_operario_relleno`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_relleno` FOREIGN KEY (`id_resolucion_relleno`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_corte` FOREIGN KEY (`id_operario_corte`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_operario_embandado` FOREIGN KEY (`id_operario_embandado`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_embandado` FOREIGN KEY (`id_resolucion_embandado`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_vulcanizado` FOREIGN KEY (`id_operario_vulcanizado`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_vulcanizado` FOREIGN KEY (`id_resolucion_vulcanizado`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_inspeccion_final` FOREIGN KEY (`id_operario_inspeccion_final`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_inspeccion_final` FOREIGN KEY (`id_resolucion_inspeccion_final`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_operario_terminacion` FOREIGN KEY (`id_operario_terminacion`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_resolucion_terminacion` FOREIGN KEY (`id_resolucion_terminacion`) REFERENCES `resoluciones_i` (`id_inspec`),
  CONSTRAINT `fk_empleado_salida` FOREIGN KEY (`id_empleado_salida`) REFERENCES `empleados` (`id_empleado`),
  CONSTRAINT `fk_bodega_salida` FOREIGN KEY (`id_bodega_salida`) REFERENCES `bodegas` (`id_bodega`),
  CONSTRAINT `fk_bodega_actual` FOREIGN KEY (`id_bodega_actual`) REFERENCES `bodegas` (`id_bodega`),
  CONSTRAINT `llantas_ibfk_1` FOREIGN KEY (`id_orden`) REFERENCES `ordenes` (`id_orden`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_2` FOREIGN KEY (`id_marca`) REFERENCES `marcas` (`id_marca`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_3` FOREIGN KEY (`id_dimension`) REFERENCES `dimensiones` (`id_dimension`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `llantas_ibfk_4` FOREIGN KEY (`id_banda`) REFERENCES `bandas` (`id_banda`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb3
